export const PATH_UNCONTROLED_FORM = 'uncontrolled-form';
export const PATH_REACT_HOOK_FORM = 'react-hook-form';

export const initialCountries = [
  'Argentina',
  'Australia',
  'Brazil',
  'Canada',
  'Chile',
  'China',
  'Colombia',
  'Cuba',
  'Ecuador',
  'Egypt',
  'France',
  'Germany',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kuwait',
  'Lebanon',
  'Malaysia',
  'Mexico',
  'Nigeria',
  'Oman',
  'Pakistan',
  'Peru',
  'Qatar',
  'Russia',
  'Saudi Arabia',
  'South Africa',
  'South Korea',
  'Spain',
  'Thailand',
  'Turkey',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'USA',
];
